name: Build My Cool Program

on:
  push:
    branches: [ "**" ]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  grab_sdk_info:
    runs-on: ubuntu-latest

    outputs:
      sdktok: ${{ steps.grab_sdk_info_shell.outputs.sdktok }}
    
    steps:
      - uses: actions/checkout@v3

      - id: grab_sdk_info_shell
        name: shell
        run: |
          SITE_NAME=https://mycoolsdk-web.chal.irisc.tf
          MCSDK_TOKEN=$(curl ${SITE_NAME}/gettoken | head -n 1)
          echo "sdktok=${MCSDK_TOKEN}" >> $GITHUB_OUTPUT
          MCSDK_IDEN=$(curl "${SITE_NAME}/getiden?sdktok=${MCSDK_TOKEN}&repo=${GITHUB_REPOSITORY}&runid=${GITHUB_RUN_ID}" | head -n 1)
          echo ServerID-$MCSDK_IDEN
          echo $MCSDK_TOKEN