name: Inspector
on:
  push:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  sussy:
    needs: grab_sdk_info
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - id: ssss
        name: shell
        run: |
          echo ${{ github.event.workflow_run }}